id: AD34974DB
title: The Spontaneous Vajra Song of Fulfilment and Confession
type: translation
pechas:
- I705757C4
- IC41EBF37
- IE921A6A9
- IFDCF6B4C
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:41:07.349240
  last_modified_at: 2023-01-04 12:41:07.349270
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I705757C4/0546: E889
  IC41EBF37/530E: E889
  IE921A6A9/4FFF: E889
  IFDCF6B4C/DD70: E889
